---
title: "Preregistration Analysis"
author: "Natalie Biderman"
date: "10/04/2021"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

Based on analysis of Pilot study.

# Setup 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r general setup, echo=FALSE, results='hide'}

rm(list=ls(all=TRUE)) 

# If packages are not installed, install. Then, load libraries. 
list_of_packages <- c("ggplot2", "cowplot", "gridExtra", "arm", "mosaic", "stringr", "tidyr", "dplyr", "bayesplot", "rstanarm", "arm", "pwr", "lme4", "lsr","kableExtra")
new_packages <- list_of_packages[!(list_of_packages %in% installed.packages()[,"Package"])]
if(length(new_packages)) install.packages(new_packages)
lapply(list_of_packages, require, character.only = TRUE)

# Load functions
source("../Analysis/Tools/plotting.R")

# Figure parameters
fig_size = c(10,10)
fig_type = "eps" # or eps
Save_plots <- 1
```

# Load data 

```{r load data and model coefs}

# Load data 
df_final_decisions <- read.csv("../Data/Summary_data/non_outlier_subs/final_decisions.csv")
df_memory <- read.csv("../Data/Summary_data/non_outlier_subs/memory.csv")

# Load models 
load("../Data/Models/M_choice_delta_val.RData")
load("../Data/Models/M_choice_RT.RData")

```

# Run Bayesian models

```{r}

# Stan parameters
options(mc.cores = parallel::detectCores())

params <- list()
params$iterations <- 4000
params$chains <- 4
params$warmup <- 2000
params$adapt_delta <- 0.99

# Create relevant columns for modeling 
df_final_decisions <- df_final_decisions %>% 
  mutate(condition_center = ifelse(condition==0, -1, 1),
         choice_center = ifelse(chosen_trial==0, -1, 1))

# Remove Non responses
df_final_decisions <- subset(df_final_decisions, !is.nan(rt))

# ====== choice ======

# Run choice model and save it
M_choice_delta_val <- stan_glmer(data = df_final_decisions, 
                                 higher_outcome_chosen ~ condition_center*choice_center*zscored_delta_ratings + (condition_center*choice_center*zscored_delta_ratings | PID),
                                 family = binomial(link="logit"), 
                                 adapt_delta = params$adapt_delta, 
                                 iter = params$iterations, 
                                 chains = params$chains, 
                                 warmup = params$warmup,
                                 seed = 12345)

save(list = "M_choice_delta_val",
     file = "../Data/Models/M_choice_delta_val.RData")

# Save posterior draws matrix
M_draws <- as.data.frame(M_choice_delta_val)
write.csv(M_draws,"../Data/Models/M_choice_delta_val_draws.csv")

# ====== RT ======

# Run RT model and save it

M_choice_RT <- stan_glmer(data = df_final_decisions, 
                             higher_outcome_chosen ~ condition_center*choice_center*zscored_rt + 
                               (condition_center*choice_center*zscored_rt | PID),
                                 family = binomial(link="logit"), 
                                 adapt_delta = params$adapt_delta, 
                                 iter = params$iterations, 
                                 chains = params$chains, 
                                 warmup = params$warmup,
                                 seed = 12345)

save(list = "M_choice_RT",
     file = "../Data/Models/M_choice_RT.RData")

# Save posterior draws matrix
M_choice_RT_draws <- as.data.frame(M_choice_RT)
write.csv(M_choice_RT_draws,"../Data/Models/M_choice_RT_draws.csv")


```

# Analysis 

## Assess choices in the Final Decisions phase

```{r}

# ========
# Behavior
# ========

df_final_decisions %>% 
  mutate(choice = ifelse(chosen_trial==1, "chosen", "unchosen"),
         condition = ifelse(condition==1, "Interference", "Repetition")) %>%
  group_by(PID, choice, condition) %>% 
  dplyr::summarise(p_gain = mean(higher_outcome_chosen, na.rm=1)) %>%
  spread(condition, p_gain) %>%
  mutate(`Condition Difference` = Interference - Repetition) %>%
  gather(key="condition", value="p_gain", Interference:`Condition Difference`) %>%
  group_by(choice, condition) %>%
  dplyr::summarise(mean = mean(p_gain),
                   se = sd(p_gain)/sqrt(n())) %>%
  mutate(text = sprintf("%.2f \u00b1 %.2f", mean, se)) %>%
  select(-c("mean","se")) %>%
  spread(condition, text)

df_final_decisions %>% 
  mutate(choice = ifelse(chosen_trial==1, "chosen", "unchosen"),
  condition = ifelse(condition==1, "Interference", "Repetition"),
  gain_chosen = ifelse(higher_outcome_chosen==1, "gain chosen", "no gain chosen")) %>%
  group_by(PID, choice, condition, gain_chosen) %>% 
  dplyr::summarise(zscored_rt = mean(zscored_rt, na.rm=1)) %>%
  spread(condition, zscored_rt) %>%
  mutate(`Condition Difference` = Interference - Repetition) %>%
  gather(key="condition", value="zscored_rt", Interference:`Condition Difference`) %>%
  group_by(choice, condition, gain_chosen) %>%
  dplyr::summarise(mean = mean(zscored_rt, na.rm=1),
                   se = sd(zscored_rt, na.rm=1)/sqrt(n())) %>%
  mutate(text = sprintf("%.2f \u00b1 %.2f", mean, se)) %>%
  select(-c("mean","se")) %>%
  spread(condition, text)

# ============
# Choice model
# ============

M_choice_delta_val_draws <- as.data.frame(M_choice_delta_val) %>%
  mutate(unchosen_intercept_interference = `(Intercept)` - choice_center + condition_center - `condition_center:choice_center`,
         unchosen_intercept_repetition = `(Intercept)` - choice_center - condition_center + `condition_center:choice_center`,
         unchosen_intercept_diff = unchosen_intercept_interference - unchosen_intercept_repetition,
         unchosen_intercept_cond = condition_center - `condition_center:choice_center`,
         unchosen_slope_interference = zscored_delta_ratings - `choice_center:zscored_delta_ratings` + `condition_center:zscored_delta_ratings` - `condition_center:choice_center:zscored_delta_ratings`,
         unchosen_slope_repetition = zscored_delta_ratings - `choice_center:zscored_delta_ratings` - `condition_center:zscored_delta_ratings` + `condition_center:choice_center:zscored_delta_ratings`,
         unchosen_slope_diff = unchosen_slope_interference - unchosen_slope_repetition)

summary_coefs <- as.data.frame(M_choice_delta_val_draws) %>%
  gather(coef, value, colnames(M_choice_delta_val_draws)[!str_detect(colnames(M_choice_delta_val_draws), "PID")]) %>%
  group_by(coef) %>%
  dplyr::summarize(HDI95_low = posterior_interval(as.matrix(value), prob=0.95)[1],
                   HDI95_high = posterior_interval(as.matrix(value), prob=0.95)[2],
                   median = median(value)) %>%
  mutate(sig = ifelse((median>0 & HDI95_low>0 & HDI95_high>0) | (median<0 & HDI95_low<0 & HDI95_high<0),"*",""),
         value = sprintf("%.2f [%.2f, %.2f]%s",median, HDI95_low, HDI95_high, sig)) %>%
  dplyr::select(coef, value) 


# ============
# RT model
# ============

M_choice_RT_draws <- as.data.frame(M_choice_RT) %>%
  mutate(unchosen_intercept_interference = `(Intercept)` - choice_center + condition_center - `condition_center:choice_center`,
         unchosen_intercept_repetition = `(Intercept)` - choice_center - condition_center + `condition_center:choice_center`,
         unchosen_intercept_diff = unchosen_intercept_interference - unchosen_intercept_repetition,
         unchosen_intercept_cond = condition_center - `condition_center:choice_center`,
         unchosen_slope_interference = zscored_rt - `choice_center:zscored_rt` + `condition_center:zscored_rt` - `condition_center:choice_center:zscored_rt`,
         unchosen_slope_repetition = zscored_rt - `choice_center:zscored_rt` - `condition_center:zscored_rt` + `condition_center:choice_center:zscored_rt`,
         unchosen_slope_diff = unchosen_slope_interference - unchosen_slope_repetition)

summary_coefs_rt <- as.data.frame(M_choice_RT_draws) %>%
  gather(coef, value, colnames(M_choice_RT_draws)[!str_detect(colnames(M_choice_RT_draws), "PID")]) %>%
  group_by(coef) %>%
  dplyr::summarize(HDI95_low = posterior_interval(as.matrix(value), prob=0.95)[1],
                   HDI95_high = posterior_interval(as.matrix(value), prob=0.95)[2],
                   median = median(value)) %>%
  mutate(sig = ifelse((median>0 & HDI95_low>0 & HDI95_high>0) | (median<0 & HDI95_low<0 & HDI95_high<0),"*",""),
         value = sprintf("%.2f [%.2f, %.2f]%s",median, HDI95_low, HDI95_high, sig)) %>%
  dplyr::select(coef, value)


```

## Assess difference in pairs memory between conditions

```{r}

df_memory %>%
  group_by(condition) %>%
  dplyr::summarise(mean = mean(pairs_acc),
                   se = sd(pairs_acc)/sqrt(n())) %>%
  mutate(text = sprintf("%.2f \u00b1 %.2f", mean, se)) %>%
  select(condition, text) 

df_memory <- mutate(df_memory,
                    condition_center = ifelse(condition==1, 1, -1))

M_pairs_memory <- stan_glmer(data = df_memory, 
                            pairs_acc ~ condition_center + (condition_center | PID),
                            family = binomial(link="logit"),  
                            adapt_delta = params$adapt_delta, 
                            iter = params$iterations, 
                            chains = params$chains, 
                            warmup = params$warmup,
                            seed = 12345)

save(list = "M_pairs_memory",
     file = "../Data/Models/M_pairs_memory.RData")

M_pairs_memory_draws <- as.data.frame(M_pairs_memory) 
M_pairs_memory_draws %>%
  gather(coef, value, colnames(M_pairs_memory_draws)[!str_detect(colnames(M_pairs_memory_draws), "PID")]) %>%
  group_by(coef) %>%
  dplyr::summarize(HDI95_low = posterior_interval(as.matrix(value), prob=0.95)[1],
                   HDI95_high = posterior_interval(as.matrix(value), prob=0.95)[2],
                   median = median(value)) %>%
  mutate(sig = ifelse((median>0 & HDI95_low>0 & HDI95_high>0) | (median<0 & HDI95_low<0 & HDI95_high<0),"*",""),
         value = sprintf("%.2f [%.2f, %.2f]%s",median, HDI95_low, HDI95_high, sig)) %>%
  dplyr::select(coef, value)

```

## Assess memory and inverse bias effects 

```{r}

# create behavioral matrix 
p_gain <- df_final_decisions %>% 
  mutate(choice = ifelse(chosen_trial==1, "chosen", "unchosen")) %>%
  group_by(PID, choice, condition) %>% 
  dplyr::summarise(p_gain = mean(higher_outcome_chosen, na.rm=1)) %>% 
  spread(choice, p_gain) %>%
  mutate(inverse_bias = chosen - unchosen)
pairs_acc <- df_memory %>%
  group_by(PID, condition) %>% 
  dplyr::summarise(pairs_acc = mean(pairs_acc, na.rm=1))
bias_memory <- merge(p_gain, pairs_acc, by=c("PID", "condition")) %>%
  mutate(condition_center = ifelse(condition == 0, -1, 1))

M_memory_bias <- stan_glm(data = bias_memory, 
                          inverse_bias ~ condition_center*pairs_acc,
                          family = gaussian(), 
                          adapt_delta = params$adapt_delta, 
                          iter = params$iterations, 
                          chains = params$chains, 
                          warmup = params$warmup,
                          seed = 12345)

save(list = "M_memory_bias",
     file = "../Data/Models/M_memory_bias.RData")

as.data.frame(M_memory_bias) %>%
  mutate(slope_interference = pairs_acc + `condition_center:pairs_acc`,
         slope_repetition = pairs_acc - `condition_center:pairs_acc`) %>%
  gather(coef, value) %>%
  group_by(coef) %>%
  dplyr::summarize(HDI95_low = posterior_interval(as.matrix(value), prob=0.95)[1],
                   HDI95_high = posterior_interval(as.matrix(value), prob=0.95)[2],
                   median = median(value)) %>%
  mutate(sig = ifelse((median>0 & HDI95_low>0 & HDI95_high>0) | (median<0 & HDI95_low<0 & HDI95_high<0),"*",""),
         value = sprintf("%.2f [%.2f, %.2f]%s",median, HDI95_low, HDI95_high, sig)) %>%
  dplyr::select(coef, value)


```

## Power analysis of Pilot data (simple logistic regressions)

```{r}

# ===================================================
# compute ttest between conditions for power analysis
# ===================================================

p_gain_unchosen <- subset(df_final_decisions, chosen_trial==0) %>% 
  mutate(condition = ifelse(condition==1, "interference", "repetition")) %>%
  group_by(PID, condition) %>% 
  dplyr::summarise(p_gain = mean(higher_outcome_chosen, na.rm=1)) %>%
  spread(condition, p_gain)

inverse_bias <- df_final_decisions %>% 
  mutate(condition = ifelse(condition==1, "interference", "repetition")) %>%
  group_by(PID, chosen_trial, condition) %>% 
  dplyr::summarise(p_gain = mean(higher_outcome_chosen, na.rm=1)) %>%
  spread(chosen_trial, p_gain) %>%
  mutate(inverse_bias = `1` - `0`) %>%
  select(-c("0","1")) %>%
  spread(condition, inverse_bias)
  

compute_power <- function(data,coef1,coef2,desired_power,desired_sig_level){
  t_stats <- data %>%
  dplyr::summarize(
    t_value = as.numeric(t.test(!!sym(coef1), !!sym(coef2), paired=TRUE)["statistic"]),
    p_value = as.numeric(t.test(!!sym(coef1), !!sym(coef2), paired=TRUE)["p.value"]),
    cohens_d = cohensD(x=!!sym(coef1),y=!!sym(coef2),method="paired"), 
    power = as.numeric(pwr.t.test(n = n(), d = cohens_d, sig.level = desired_sig_level, 
                       type = c("paired"))["power"]),
    desired_sample = as.numeric(pwr.t.test(power = desired_power, d = cohens_d, 
                                sig.level = desired_sig_level, type = c("paired"))["n"]))
  return(t_stats)
}

power_pilot_unchosen <- compute_power(p_gain_unchosen[,2:3], "interference", "repetition", 0.99, 0.05)
power_pilot_inverse_bias <- compute_power(inverse_bias[,2:3], "interference", "repetition", 0.99, 0.05)


# ========================================================
# run simple logistic regressions to predict decision bias
# ========================================================

df_final_decisions <- subset(df_final_decisions, !is.na(left_chosen)) %>%
  mutate(choice_center = ifelse(chosen_trial==1, 1, -1),
         condition_center = ifelse(condition==1, 1, -1))

# run logistic fits for each subject and detect their unchosen intercept
subs <- unique(df_final_decisions$PID)
subs_coefs <- data.frame()
for (i in 1:length(subs)){
  sub_data <- subset(df_final_decisions, PID == subs[i])
  m_sub <- glm(data = sub_data, 
                higher_outcome_chosen ~ condition_center * choice_center * zscored_delta_ratings, 
                family = binomial())
  subs_coefs[i,1] <- subs[i]
  subs_coefs[i,2:9] <- m_sub$coefficients
}
colnames(subs_coefs) <- c("PID",rownames(as.data.frame(m_sub$coefficients)))

p1 <- ggplot(data=sub_data, aes(y=higher_outcome_chosen,x=zscored_delta_ratings,color=condition)) + 
  stat_smooth(method="glm", method.args=list(family="binomial"), 
              na.rm=TRUE, se=FALSE, alpha=0.3, size=0.5) + 
  theme(legend.position="top") + 
  geom_hline(yintercept=0.5, linetype="dashed", size=0.5) + 
  geom_vline(xintercept=0, linetype="dashed", size=0.5) + 
  facet_grid(.~chosen_trial)


# compute unchosen intercept for the difference between the two conditions
subs_coefs <- mutate(subs_coefs, 
                     unchosen_intercept_interference = `(Intercept)` - choice_center + condition_center - `condition_center:choice_center`,
         unchosen_intercept_repetition = `(Intercept)` - choice_center - condition_center + `condition_center:choice_center`,
         unchosen_intercept_diff = unchosen_intercept_interference - unchosen_intercept_repetition,
         unchosen_intercept_cond = condition_center - `condition_center:choice_center`,
         unchosen_slope_interference = zscored_delta_ratings - `choice_center:zscored_delta_ratings` + `condition_center:zscored_delta_ratings` - `condition_center:choice_center:zscored_delta_ratings`,
         unchosen_slope_repetition = zscored_delta_ratings - `choice_center:zscored_delta_ratings` - `condition_center:zscored_delta_ratings` + `condition_center:choice_center:zscored_delta_ratings`,
         unchosen_slope_diff = unchosen_slope_interference - unchosen_slope_repetition)

# compute power
power_pilot_logistic <- compute_power(subs_coefs, "unchosen_intercept_interference", "unchosen_intercept_repetition", 0.99, 0.05)

# ========================================
# assess rt effects of choosing gain items 
# ========================================

rt_choose_gain <- df_final_decisions %>%
  mutate(choice = ifelse(chosen_trial==1, "chosen", "unchosen"),
          condition = ifelse(condition==1, "interference", "repetition"),
         choose_gain = ifelse(higher_outcome_chosen==1, "choose gain", "choose no gain")) %>%
  group_by(PID, choice, condition, choose_gain) %>% 
  dplyr::summarise(zscored_rt = mean(zscored_rt, na.rm=1)) 

t.test(rt_choose_gain$zscored_rt[rt_choose_gain$choice=="unchosen" & rt_choose_gain$condition == "repetition" & rt_choose_gain$choose_gain == "choose gain"], 
       rt_choose_gain$zscored_rt[rt_choose_gain$choice=="unchosen" & rt_choose_gain$condition == "repetition" & rt_choose_gain$choose_gain == "choose no gain"], 
       paired=TRUE)

## 

subs_coefs_bayesian <- coef(M_choice_delta_val)
subs_coefs_bayesian <- subs_coefs_bayesian$PID 
subs_coefs_bayesian <- subs_coefs_bayesian %>%
  mutate(unchosen_intercept_interference = `(Intercept)` - choice_center + condition_center - `condition_center:choice_center`,
         unchosen_intercept_repetition = `(Intercept)` - choice_center - condition_center + `condition_center:choice_center`,
         unchosen_intercept_diff = unchosen_intercept_interference - unchosen_intercept_repetition,
         unchosen_intercept_cond = condition_center - `condition_center:choice_center`,
         unchosen_slope_interference = zscored_delta_ratings - `choice_center:zscored_delta_ratings` + `condition_center:zscored_delta_ratings` - `condition_center:choice_center:zscored_delta_ratings`,
         unchosen_slope_repetition = zscored_delta_ratings - `choice_center:zscored_delta_ratings` - `condition_center:zscored_delta_ratings` + `condition_center:choice_center:zscored_delta_ratings`,
         unchosen_slope_diff = unchosen_slope_interference - unchosen_slope_repetition)

power_pilot_logistic <- compute_power(subs_coefs_bayesian, "unchosen_intercept_interference", "unchosen_intercept_repetition", 0.99, 0.05)


```


